CREATE DATABASE IF NOT EXISTS materiel_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE materiel_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS materiel (
  n_materiel INT AUTO_INCREMENT PRIMARY KEY,
  design VARCHAR(100) NOT NULL,
  etat ENUM('Bon', 'Mauvais', 'Abîmé') NOT NULL,
  quantite INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
